[workspace]
members = ["feed-handler"]
resolver = "2"
version = "0.1.0"

[workspace.dependencies]
tokio = {version = "1.47.1", features = ["full"]}
serde = {version = "1.0.219", features = ["derive"]}

futures-util = "0.3.31"
serde_json = "1.0.143"
async-nats = "0.42.0"