version: '3.8'

services:
  nats:
    image: nats:2.11.8-alpine3.22
    ports:
      - "4222:4222"
      - "8222:8222"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.15
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  clickhouse:
    image: clickhouse/clickhouse-server:22.5.3-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
    - ./clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse", "client", "-q", "SELECT 1"]
      interval: 30s
      timeout: 5s
      retries: 3