[watch]
# Paths to watch for changes.
watch = ["."]

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 3000
# Open a browser tab when the server starts.
open = true

